exclude: ^(docs|tests/files|tasks.py)

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "main"
    hooks:
      - id: ruff

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest
        language: system
        types: [python]
