[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "molgeom"
version = "0.2.2"
description = "A simple molecular geometry manipulation module"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "cachetools>=5.5.0",
    "networkx>=2.6.3",
    "pyyaml>=6.0.1",
]
authors = [
    { name = "sio-salt", email = "saltinthedesertyou@gmail.com" }
]

[tool.setuptools.packages.find]
where = ["."]
include = ["molgeom*"]

[tool.uv]
dev-dependencies = [
    "icecream>=2.1.3",
    "pytest-timeout>=2.3.1",
    "pytest>=7.4.4",
    "isort>=5.13.2",
]

