[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "molgeom"
version = "0.2.0"
description = "A simple molecular geometry manipulation module"
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
    "easyvec>=0.1.0",
    "networkx>=2.6.3",
    "pyyaml>=6.0.1",
]
authors = [
    { name = "Yo Kato", email = "saltinthedesertyou@gmail.com" }
]

[tool.setuptools]
packages = ["molgeom"]

[tool.uv.sources]
easyvec = { path = "../easyvec" }

