[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "molgeom"
version = "0.3.0"
description = "A simple molecular geometry manipulation module"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "cachetools>=5.5.0",
    "networkx>=2.6.3",
    "pyyaml>=6.0.1",
]
authors = [
    { name = "sio-salt", email = "saltinthedesertyou@gmail.com" }
]

[project.scripts]
mass-center = "molgeom.interfaces.mass_center:main"
nuclear-repulsion = "molgeom.interfaces.nuclear_repulsion:main"
mol-bonds = "molgeom.interfaces.mol_bonds:main"
geom-modifier = "molgeom.interfaces.geom_modifier:main"
poscar-to-xyz = "molgeom.interfaces.poscar2xyz:main"
split-mol-clusters = "molgeom.interfaces.split_mol_clusters:main"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]
include = ["molgeom*"]

[tool.setuptools.package-data]
"molgeom" = ["data/*.json", "data/*.yaml"]


[tool.uv]
dev-dependencies = [
    "icecream>=2.1.3",
    "pytest-timeout>=2.3.1",
    "pytest>=7.4.4",
    "isort>=5.13.2",
]

