name: Publish molgeom to PyPI

on:
  release:
    types: ["published"]

jobs:
  run:
    name: "Build and publish to PyPI"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: uv.lock

      - name: Set up Python
        run: uv python install 3.12

      - name: Build
        run: uv build

      - name: Publish
        run: uv publish --token ${{ secrets.molgeom_PYPI_TOKEN }}
